# Generated by Django 5.1.1 on 2024-09-29 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('daraja', models.CharField(choices=[('Yengil', 'Yengil'), ("O'rta", "O'rta"), ('Yuqori', 'Yuqori')], default='Yuqori', max_length=50)),
                ('ustoz', models.CharField(max_length=255)),
                ('narx', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('chegirma', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(blank=True, null=True)),
                ('baho', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)])),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(choices=[("To'lov kutilmoqda", "To'lov kutilmoqda"), ("To'landi", "To'landi")], default="To'lov kutilmoqda", max_length=50)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.profil')),
            ],
        ),
    ]
